-- 코드를 입력하세요
# 음식종류별 즐겨찾기 수가 가장 많은 식당의 음식 종류
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS "A"
    FROM REST_INFO
    GROUP BY FOOD_TYPE) M
ON R.FOOD_TYPE = M.FOOD_TYPE AND R.FAVORITES = M.A
ORDER BY FOOD_TYPE DESC