-- 코드를 작성해주세요
SELECT T.QUARTER, COUNT(*) AS "ECOLI_COUNT"
FROM (SELECT CASE 
           WHEN MONTH(DIFFERENTIATION_DATE) < 4 THEN '1Q'
           WHEN MONTH(DIFFERENTIATION_DATE) < 7 THEN '2Q'
           WHEN MONTH(DIFFERENTIATION_DATE) < 10 THEN '3Q'
           WHEN MONTH(DIFFERENTIATION_DATE) < 13 THEN '4Q'
           END AS QUARTER,
       ID
FROM ECOLI_DATA) T
GROUP BY T.QUARTER
ORDER BY T.QUARTER