-- 코드를 작성해주세요
SELECT R.ITEM_ID, R.ITEM_NAME, R.RARITY
FROM ITEM_TREE T
LEFT JOIN ITEM_INFO I
ON T.PARENT_ITEM_ID = I.ITEM_ID
JOIN ITEM_INFO R
ON T.ITEM_ID = R.ITEM_ID
WHERE I.RARITY = "RARE"
ORDER BY R.ITEM_ID DESC