-- 코드를 작성해주세요
SELECT N.ID AS ID, N.GENOTYPE AS GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA N
JOIN ECOLI_DATA P
ON N.PARENT_ID = P.ID
WHERE (N.GENOTYPE & P.GENOTYPE) = P.GENOTYPE
ORDER BY N.ID