-- 코드를 입력하세요
# 2022-8 ~ 2022-10 총 대여 회수 5회 이상
# 위에 해당하는 애들만 해당 기간동안 월별 자동차 ID별 총 대여 횟수
SELECT MONTH(START_DATE) AS "MONTH", CAR_ID, COUNT(*) AS "RECORDS"
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= "2022-08-01" AND START_DATE < "2022-11-01"
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5)
    AND START_DATE >= "2022-08-01" AND START_DATE < "2022-11-01"
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH, CAR_ID DESC