-- 코드를 입력하세요
# 세단, 10월 대여 기록,
SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C
ON C.CAR_ID = H.CAR_ID
WHERE CAR_TYPE = "세단" AND MONTH(H.START_DATE) = 10
ORDER BY CAR_ID DESC