-- 코드를 입력하세요
# 성분 타입 구별로 총 주문량
# 정렬은 총 주문량
SELECT I.INGREDIENT_TYPE, SUM(T) AS "TOTAL_ORDER"
FROM ICECREAM_INFO I
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS "T"
    FROM FIRST_HALF
    GROUP BY FLAVOR) F
ON I.FLAVOR = F.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER