-- 코드를 작성해주세요
SELECT D.DEPT_ID, N.DEPT_NAME_EN, D.AVG_SAL
FROM (SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS "AVG_SAL"
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID) D
JOIN HR_DEPARTMENT N
ON D.DEPT_ID = N.DEPT_ID
ORDER BY AVG_SAL DESC