-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES) AS "SALES"
FROM BOOK B
JOIN (SELECT BOOK_ID, SUM(SALES) AS "SALES"
FROM BOOK_SALES
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY BOOK_ID) S
ON B.BOOK_ID = S.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY